uxitter/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  resources :posts, only: %i[index new create show destroy] do
    member do
      post :good
    end
  end
  resources :words
end

uxitter/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

uxitter/app/models/post.rb
class Post < ApplicationRecord
  validates :before, :after, presence: true
  validates :before, :after, length: { maximum: 250 }

  def self.exchange(post_params)
    exchange_params = post_params
    text = post_params[:before]
    after_text = text.gsub(/します/, "するます")
    exchange_params[:after] = after_text
    return exchange_params
  end
end

uxitter/app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, :name, uniqueness: true, presence: true

  enum role: { general: 0, admin: 1 }
end

uxitter/app/models/word.rb
class Word < ApplicationRecord
  validates :input, :output, presence: true
end

uxitter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

uxitter/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top; end
end

uxitter/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order(count: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    exchange_params = Post.exchange(post_params)
    @post = Post.new(exchange_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def good
    @post = Post.find(params[:id])
    @post.update(count: @post.count + 1)
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:name, :before)
  end
end

uxitter/app/controllers/words_controller.rb
class WordsController < ApplicationController
end

uxitter/app/helpers/application_helper.rb
module ApplicationHelper
end

uxitter/app/helpers/homes_helper.rb
module HomesHelper
end

uxitter/app/helpers/posts_helper.rb
module PostsHelper
end

uxitter/app/helpers/words_helper.rb
module WordsHelper
end

uxitter/app/views/homes/top.html.erb
<div class="title-block">
  <div class="title"><h1>ういったー</h1></div>
</div>

<div class="main-section">
  <%= link_to "新規投稿ます", new_post_path, class: "btn" %>
</div>

uxitter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uxitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

uxitter/app/views/posts/good.js.erb
document.getElementById("post_<%= @post.id %>").textContent  = "<%= @post.count %>";

uxitter/app/views/posts/index.html.erb
<div class="title-block">
  <div class="title"><h1>いちらん</h1></div>
</div>

<div class="main-section">
  <div class="post-list">
    <% @posts.each do |post| %>
      <div class="post-card after">
        <div class="post-card-body">
          <div class="post-name">
            <% if post.name.present? %>
              <%= post.name %>
            <% else %>
              ゲスト
            <% end %>
          </div>
          <div class="post-content"><%= link_to "#{post.after}", post_path(post) %></div>
        </div>
        <div class="post-card-footer">
          <div class="post-action" id="post_<%= post.id %>"><%= post.count %></div>
          <div class="post-action">
            <%= link_to good_post_path(post), method: :post, remote: true do %>
              <i class="fas fa-heart"></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

uxitter/app/views/posts/new.html.erb
<div class="title-block">
  <div class="title"><h1>へんかん</h1></div>
</div>

<div class="main-section">
  <div class="post-form">
    <%= form_with model: @post, url: posts_path, local: true do |f| %>
      <div class="form-item">
        <%= f.label :name, "ニックネーム", class: "label" %>
        <%= f.text_field :name, class: "form form-name" %>
      </div>
      <div class="form-item">
        <%= f.label :before, "テキスト", class: "label" %>
        <%= f.text_area :before, class: "form form-content" %>
      </div>
      <div class="submit">
        <%= f.submit '変換ます', class: "btn" %>
      </div>
    <% end %>
  </div>
</div>

uxitter/app/views/posts/show.html.erb
<div class="title-block">
  <div class="title"><h1>しょーさい</h1></div>
</div>

<div class="main-section">
  <div class="post-list">
    <div class="post-card before">
      <div class="post-card-body">
        <div class="post-name">
          <% if @post.name.present? %>
            <%= @post.name %>
          <% else %>
            ゲスト
          <% end %>
        </div>
        <div class="post-content"><%= @post.before %></div>
      </div>
    </div>
  </div>
</div>

<div class="gap"><i class="fas fa-arrow-alt-circle-down"></i></div>

<div class="main-section">
  <div class="post-list">
    <div class="post-card after">
      <div class="post-card-body">
        <div class="post-name">
          <% if @post.name.present? %>
            <%= @post.name %>
          <% else %>
            ゲスト
          <% end %>
        </div>
        <div class="post-content"><%= @post.after %></div>
      </div>
      <div class="post-card-footer">
        <div class="post-action" id="post_<%= @post.id %>"><%= @post.count %></div>
        <div class="post-action">
          <%= link_to good_post_path(@post), method: :post, remote: true do %>
            <i class="fas fa-heart"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

uxitter/app/views/shared/_header.html.erb
<header>
  <ul>
    <li><%= link_to 'ほーむ', root_path %></li>
    <li><%= link_to 'へんかん', new_post_path %></li>
    <li><%= link_to 'いちらん', posts_path %></li>
  </ul>
</header>